version: '3.7'

services:

  bfddb:
    image: postgres:9.6
    environment:
      POSTGRES_DB: bfd
      POSTGRES_USER: bfd
      POSTGRES_PASSWORD: InsecureLocalDev
  bfd:
    build:
      context: .
      dockerfile: Dockerfile
    user: dev
    working_dir: /code
    command: make docker
    volumes:
      - .:/code
    environment:
      JAVA_HOME: "/usr/lib/jvm/java-1.8.0-openjdk-amd64/"
      BFD_PORT: 9954
      LOCAL_SYNTHETIC_DATA: "/code/synthetic-data"
    ports:
      - "1337:9954"
    depends_on:
      - bfddb
  bbdb:
    image: postgres
    environment:
      - POSTGRES_DB=bluebutton
      - POSTGRES_PASSWORD=toor
  bb20:
    build:
      context: ${CONTEXT}
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=hhs_oauth_server.settings.dev
      - DATABASES_CUSTOM=postgres://postgres:toor@bbdb:5432/bluebutton
      - OAUTHLIB_INSECURE_TRANSPORT=true
      - DJANGO_DEFAULT_SAMPLE_FHIR_ID="20140000008325"
      - DJANGO_SECURE_SESSION=False
    ports:
      - "8000:8000"
    links:
      - "bfd:bfd.local"
    volumes:
      - ${CONTEXT}:/code
      - ./certstore:/certstore
    depends_on:
      - bbdb
